### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by Saad-ilyas** [Svision/CoRider#1]
One file is missing in this project. please upload the location file.

**Comment by Svision** [comment]
I believe location is the package

**Comment by Saad-ilyas** [comment]
Basically, it gives me an error when I run this project. and the error is location files are missing Sent from Mail for Windows From: Changhao SongSent: 05 June 2023 21:08To: Svision/CoRiderCc: Muhammad Saad Ilyas; AuthorSubject: Re: [Svision/CoRider] File Missing (Issue #1) I believe location is the package—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Svision** [comment]
I am not seeing the error from my local machine, and I also introduced the CI. The CI passed without any problem. Please specify the error message or screenshot.

**Comment by Saad-ilyas** [comment]
[image: image.png]

**Comment by Svision** [comment]
> 

It is not visible
